github:
  prebuilds:
    addComment: false
    addBadge: true

ports:
  - port: 8080-8081
    onOpen: open-browser

tasks:
  - init: |
      cd /workspace
      git clone https://github.com/Mathics3/mathicsscript
      cd mathicsscript
      make
      make install

      cd /workspace
      git clone https://github.com/Mathics3/mathics-django
      cd mathics-django
      make
      make install

      cd /workspace
      git clone https://github.com/Mathics3/mathics-benchmark
      cd mathics-benchmark
      sudo apt install python3.8-venv -y
      PYTHON=python3 ./admin-tools/install-venv.sh
      make

      cd /workspace/mathics-core
      make
      make install

    command: mathics
