(* Math7 *)

{"8Bit",
{
{65, "\[DoubleStruckCapitalA]"},
{66, "\[DoubleStruckCapitalB]"},
{67, "\[DoubleStruckCapitalC]"},
{68, "\[DoubleStruckCapitalD]"},
{69, "\[DoubleStruckCapitalE]"},
{70, "\[DoubleStruckCapitalF]"},
{71, "\[DoubleStruckCapitalG]"},
{72, "\[DoubleStruckCapitalH]"},
{73, "\[DoubleStruckCapitalI]"},
{74, "\[DoubleStruckCapitalJ]"},
{75, "\[DoubleStruckCapitalK]"},
{76, "\[DoubleStruckCapitalL]"},
{77, "\[DoubleStruckCapitalM]"},
{78, "\[DoubleStruckCapitalN]"},
{79, "\[DoubleStruckCapitalO]"},
{80, "\[DoubleStruckCapitalP]"},
{81, "\[DoubleStruckCapitalQ]"},
{82, "\[DoubleStruckCapitalR]"},
{83, "\[DoubleStruckCapitalS]"},
{84, "\[DoubleStruckCapitalT]"},
{85, "\[DoubleStruckCapitalU]"},
{86, "\[DoubleStruckCapitalV]"},
{87, "\[DoubleStruckCapitalW]"},
{88, "\[DoubleStruckCapitalX]"},
{89, "\[DoubleStruckCapitalY]"},
{90, "\[DoubleStruckCapitalZ]"},
{97, "\[DoubleStruckA]"},
{98, "\[DoubleStruckB]"},
{99, "\[DoubleStruckC]"},
{100, "\[DoubleStruckD]"},
{101, "\[DoubleStruckE]"},
{102, "\[DoubleStruckF]"},
{103, "\[DoubleStruckG]"},
{104, "\[DoubleStruckH]"},
{105, "\[DoubleStruckI]"},
{106, "\[DoubleStruckJ]"},
{107, "\[DoubleStruckK]"},
{108, "\[DoubleStruckL]"},
{109, "\[DoubleStruckM]"},
{110, "\[DoubleStruckN]"},
{111, "\[DoubleStruckO]"},
{112, "\[DoubleStruckP]"},
{113, "\[DoubleStruckQ]"},
{114, "\[DoubleStruckR]"},
{115, "\[DoubleStruckS]"},
{116, "\[DoubleStruckT]"},
{117, "\[DoubleStruckU]"},
{118, "\[DoubleStruckV]"},
{119, "\[DoubleStruckW]"},
{120, "\[DoubleStruckX]"},
{121, "\[DoubleStruckY]"},
{122, "\[DoubleStruckZ]"}
}
}
