"""
Test precedences
"""

from test.helper import check_evaluation, evaluate, session

import pytest


@pytest.mark.parametrize(
    (
        "symbol",
        "prec",
    ),
    [
        (
            "Therefore",
            50.0,
        ),
        (
            "Because",
            50.0,
        ),
        (
            "Colon",
            80.0,
        ),
        (
            "SuchThat",
            180.0,
        ),
        (
            "UpTee",
            190.0,
        ),
        (
            "RightTee",
            190.0,
        ),
        (
            "Perpendicular",
            190.0,
        ),
        (
            "LeftTee",
            190.0,
        ),
        (
            "DownTee",
            190.0,
        ),
        (
            "DoubleRightTee",
            190.0,
        ),
        (
            "DoubleLeftTee",
            190.0,
        ),
        # According WMA, And and Or has
        # the same precedence. However,
        # This is mathematically wrong.
        (
            "Or",
            215.0,
        ),
        (
            "And",
            215.0,
        ),
        (
            "Not",
            230.0,
        ),
        (
            "RoundImplies",
            240.0,
        ),
        (
            "SupersetEqual",
            250.0,
        ),
        (
            "Superset",
            250.0,
        ),
        (
            "SubsetEqual",
            250.0,
        ),
        (
            "Subset",
            250.0,
        ),
        (
            "SquareSupersetEqual",
            250.0,
        ),
        (
            "SquareSuperset",
            250.0,
        ),
        (
            "SquareSubsetEqual",
            250.0,
        ),
        (
            "SquareSubset",
            250.0,
        ),
        (
            "ReverseElement",
            250.0,
        ),
        (
            "NotSupersetEqual",
            250.0,
        ),
        (
            "NotSuperset",
            250.0,
        ),
        (
            "NotSubsetEqual",
            250.0,
        ),
        (
            "NotSubset",
            250.0,
        ),
        (
            "NotSquareSupersetEqual",
            250.0,
        ),
        (
            "NotSquareSubsetEqual",
            250.0,
        ),
        (
            "NotReverseElement",
            250.0,
        ),
        (
            "UpperRightArrow",
            270.0,
        ),
        (
            "UpperLeftArrow",
            270.0,
        ),
        (
            "ShortRightArrow",
            270.0,
        ),
        (
            "ShortLeftArrow",
            270.0,
        ),
        (
            "RightVectorBar",
            270.0,
        ),
        (
            "RightVector",
            270.0,
        ),
        (
            "RightTeeVector",
            270.0,
        ),
        (
            "RightTeeArrow",
            270.0,
        ),
        (
            "RightArrowLeftArrow",
            270.0,
        ),
        (
            "RightArrowBar",
            270.0,
        ),
        (
            "RightArrow",
            270.0,
        ),
        (
            "LowerRightArrow",
            270.0,
        ),
        (
            "LowerLeftArrow",
            270.0,
        ),
        (
            "LeftVectorBar",
            270.0,
        ),
        (
            "LeftVector",
            270.0,
        ),
        (
            "LeftTeeVector",
            270.0,
        ),
        (
            "LeftTeeArrow",
            270.0,
        ),
        (
            "LeftRightVector",
            270.0,
        ),
        (
            "LeftRightArrow",
            270.0,
        ),
        (
            "LeftArrowRightArrow",
            270.0,
        ),
        (
            "LeftArrowBar",
            270.0,
        ),
        (
            "LeftArrow",
            270.0,
        ),
        (
            "DownRightVectorBar",
            270.0,
        ),
        (
            "DownRightVector",
            270.0,
        ),
        (
            "DownRightTeeVector",
            270.0,
        ),
        (
            "DownLeftVectorBar",
            270.0,
        ),
        (
            "DownLeftVector",
            270.0,
        ),
        (
            "DownLeftTeeVector",
            270.0,
        ),
        (
            "DownLeftRightVector",
            270.0,
        ),
        (
            "DoubleRightArrow",
            270.0,
        ),
        (
            "DoubleLeftRightArrow",
            270.0,
        ),
        (
            "DoubleLeftArrow",
            270.0,
        ),
        (
            "VerticalBar",
            280.0,
        ),
        (
            "NotDoubleVerticalBar",
            280.0,
        ),
        (
            "DoubleVerticalBar",
            280.0,
        ),
        (
            "TildeTilde",
            290.0,
        ),
        (
            "TildeFullEqual",
            290.0,
        ),
        (
            "TildeEqual",
            290.0,
        ),
        (
            "Tilde",
            290.0,
        ),
        (
            "SucceedsTilde",
            290.0,
        ),
        (
            "SucceedsSlantEqual",
            290.0,
        ),
        (
            "SucceedsEqual",
            290.0,
        ),
        (
            "Succeeds",
            290.0,
        ),
        (
            "RightTriangleEqual",
            290.0,
        ),
        (
            "RightTriangleBar",
            290.0,
        ),
        (
            "RightTriangle",
            290.0,
        ),
        (
            "ReverseEquilibrium",
            290.0,
        ),
        (
            "Proportional",
            290.0,
        ),
        (
            "Proportion",
            290.0,
        ),
        (
            "PrecedesTilde",
            290.0,
        ),
        (
            "PrecedesSlantEqual",
            290.0,
        ),
        (
            "PrecedesEqual",
            290.0,
        ),
        (
            "Precedes",
            290.0,
        ),
        (
            "NotTildeTilde",
            290.0,
        ),
        (
            "NotTildeFullEqual",
            290.0,
        ),
        (
            "NotTildeEqual",
            290.0,
        ),
        (
            "NotTilde",
            290.0,
        ),
        (
            "NotSucceedsTilde",
            290.0,
        ),
        (
            "NotSucceedsSlantEqual",
            290.0,
        ),
        (
            "NotSucceeds",
            290.0,
        ),
        (
            "NotRightTriangleEqual",
            290.0,
        ),
        (
            "NotRightTriangle",
            290.0,
        ),
        (
            "NotPrecedesTilde",
            290.0,
        ),
        (
            "NotPrecedesSlantEqual",
            290.0,
        ),
        (
            "NotPrecedes",
            290.0,
        ),
        (
            "NotLessTilde",
            290.0,
        ),
        (
            "NotLessGreater",
            290.0,
        ),
        (
            "NotLessFullEqual",
            290.0,
        ),
        (
            "NotLessEqual",
            290.0,
        ),
        (
            "NotLess",
            290.0,
        ),
        (
            "NotLeftTriangleEqual",
            290.0,
        ),
        (
            "NotLeftTriangle",
            290.0,
        ),
        (
            "NotGreaterTilde",
            290.0,
        ),
        (
            "NotGreaterLess",
            290.0,
        ),
        (
            "NotGreaterFullEqual",
            290.0,
        ),
        (
            "NotGreaterEqual",
            290.0,
        ),
        (
            "NotGreater",
            290.0,
        ),
        (
            "NotCupCap",
            290.0,
        ),
        (
            "NotCongruent",
            290.0,
        ),
        (
            "NestedLessLess",
            290.0,
        ),
        (
            "NestedGreaterGreater",
            290.0,
        ),
        (
            "LessTilde",
            290.0,
        ),
        (
            "LessLess",
            290.0,
        ),
        (
            "LessGreater",
            290.0,
        ),
        (
            "LessFullEqual",
            290.0,
        ),
        (
            "LessEqualGreater",
            290.0,
        ),
        (
            "LeftTriangleEqual",
            290.0,
        ),
        (
            "LeftTriangleBar",
            290.0,
        ),
        (
            "LeftTriangle",
            290.0,
        ),
        (
            "HumpEqual",
            290.0,
        ),
        (
            "HumpDownHump",
            290.0,
        ),
        (
            "GreaterTilde",
            290.0,
        ),
        (
            "GreaterLess",
            290.0,
        ),
        (
            "GreaterGreater",
            290.0,
        ),
        (
            "GreaterFullEqual",
            290.0,
        ),
        (
            "GreaterEqualLess",
            290.0,
        ),
        (
            "Equilibrium",
            290.0,
        ),
        (
            "EqualTilde",
            290.0,
        ),
        (
            "DotEqual",
            290.0,
        ),
        (
            "CupCap",
            290.0,
        ),
        (
            "Congruent",
            290.0,
        ),
        (
            "Greater",
            290.0,
        ),
        (
            "GreaterEqual",
            290.0,
        ),
        (
            "LessEqual",
            290.0,
        ),
        (
            "Equal",
            290.0,
        ),
        (
            "UnionPlus",
            300.0,
        ),
        (
            "SquareUnion",
            300.0,
        ),
        (
            "SquareIntersection",
            305.0,
        ),
        (
            "PlusMinus",
            310.0,
        ),
        (
            "MinusPlus",
            310.0,
        ),
        (
            "Plus",
            310.0,
        ),
        (
            "CirclePlus",
            330.0,
        ),
        (
            "CircleMinus",
            330.0,
        ),
        (
            "Cup",
            340.0,
        ),
        (
            "Cap",
            350.0,
        ),
        (
            "Coproduct",
            360.0,
        ),
        (
            "VerticalTilde",
            370.0,
        ),
        (
            "Star",
            390.0,
        ),
        (
            "Times",
            400.0,
        ),
        (
            "CenterDot",
            410.0,
        ),
        (
            "CircleTimes",
            420.0,
        ),
        (
            "Vee",
            430.0,
        ),
        (
            "Wedge",
            440.0,
        ),
        (
            "Diamond",
            450.0,
        ),
        (
            "Backslash",
            460.0,
        ),
        (
            "Divide",
            470.0,
        ),
        (
            "Minus",
            480.0,
        ),
        (
            "CircleDot",
            520.0,
        ),
        (
            "SmallCircle",
            530.0,
        ),
        (
            "Square",
            540.0,
        ),
        (
            "DifferentialD",
            550.0,
        ),
        (
            "Del",
            550.0,
        ),
        (
            "CapitalDifferentialD",
            550.0,
        ),
        (
            "UpTeeArrow",
            580.0,
        ),
        (
            "UpEquilibrium",
            580.0,
        ),
        (
            "UpDownArrow",
            580.0,
        ),
        (
            "UpArrowDownArrow",
            580.0,
        ),
        (
            "UpArrowBar",
            580.0,
        ),
        (
            "UpArrow",
            580.0,
        ),
        (
            "ShortUpArrow",
            580.0,
        ),
        (
            "ShortDownArrow",
            580.0,
        ),
        (
            "RightUpVectorBar",
            580.0,
        ),
        (
            "RightUpVector",
            580.0,
        ),
        (
            "RightUpTeeVector",
            580.0,
        ),
        (
            "RightUpDownVector",
            580.0,
        ),
        (
            "RightDownVectorBar",
            580.0,
        ),
        (
            "RightDownVector",
            580.0,
        ),
        (
            "RightDownTeeVector",
            580.0,
        ),
        (
            "ReverseUpEquilibrium",
            580.0,
        ),
        (
            "LongRightArrow",
            580.0,
        ),
        (
            "LongLeftRightArrow",
            580.0,
        ),
        (
            "LongLeftArrow",
            580.0,
        ),
        (
            "LeftUpVectorBar",
            580.0,
        ),
        (
            "LeftUpVector",
            580.0,
        ),
        (
            "LeftUpTeeVector",
            580.0,
        ),
        (
            "LeftUpDownVector",
            580.0,
        ),
        (
            "LeftDownVectorBar",
            580.0,
        ),
        (
            "LeftDownVector",
            580.0,
        ),
        (
            "LeftDownTeeVector",
            580.0,
        ),
        (
            "DownTeeArrow",
            580.0,
        ),
        (
            "DownArrowUpArrow",
            580.0,
        ),
        (
            "DownArrowBar",
            580.0,
        ),
        (
            "DownArrow",
            580.0,
        ),
        (
            "DoubleUpDownArrow",
            580.0,
        ),
        (
            "DoubleUpArrow",
            580.0,
        ),
        (
            "DoubleLongRightArrow",
            580.0,
        ),
        (
            "DoubleLongLeftRightArrow",
            580.0,
        ),
        (
            "DoubleLongLeftArrow",
            580.0,
        ),
        (
            "DoubleDownArrow",
            580.0,
        ),
        (
            "Power",
            590.0,
        ),
        (
            "Apply",
            620.0,
        ),
        (
            "InvisiblePrefixScriptBase",
            670.0,
        ),
        (
            "InvisiblePostfixScriptBase",
            670.0,
        ),
        (
            "LessSlantEqual",
            670.0,
        ),
        (
            "GreaterSlantEqual",
            670.0,
        ),
        (
            "AppendTo",
            670.0,
        ),
        (
            "Part",
            670.0,
        ),
    ],
)
def test_precedence_values(symbol, prec):
    """

    TrueRelPrecedence[op1_, op2_] :=
             Module[{formatted =
                     ToString[
               HoldForm[ope2[ope1[a, b], c]] /. {ope1 -> op1, ope2 -> op2},
               InputForm]},
                Not[Or[StringPart[formatted, 1] == "(",
                StringPart[formatted, -1] == ")"]]]

    Transpose[{a, ALLOPS}] // TableForm"""

    mathics_prec = session.evaluate(f"Precedence[{symbol}]").value
    print("Check", f"Precedence[{symbol}]=={prec}")
    check_evaluation(
        f"Precedence[{symbol}]=={prec}",
        "True",
        to_string_expr=True,
        to_string_expected=True,
        hold_expected=True,
        failure_message=f"Precendece of {symbol} in mathics {mathics_prec} !=  WMA value {prec}",
        expected_messages=None,
    )
