import os
import subprocess
from test.helper import session

import mathics.builtin.drawing.plot as plot
from mathics.core.util import print_expression_tree

both = [
    ("test-plot3d", "Plot3D[x y, {x,0,1}, {y,0,1}]"),
]

classic = [
    ("test-plot", "Plot[x, {x,0,1}]"),
]

vectorized = [
    ("test-density", "DensityPlot[x y, {x,0,1}, {y,0,1}]"),
]


def ref_dir():
    dir, _ = os.path.splitext(__file__)
    return dir + "_ref"


def one_test(name, str_expr, act_dir="/tmp"):
    print(f"=== running {name} {str_expr}")

    # evaluate the expression to be tested
    expr = session.parse(str_expr)
    act_expr = expr.evaluate(session.evaluation)

    # write the results to act_fn in act_dir
    act_fn = os.path.join(act_dir, f"{name}.txt")
    with open(act_fn, "w") as act_f:
        print_expression_tree(act_expr, file=act_f)

    # use diff to compare the actual result in act_fn to reference result in ref_fn

    ref_fn = os.path.join(ref_dir(), f"{name}.txt")
    result = subprocess.run(["diff", "-u", ref_fn, act_fn], capture_output=False)
    assert result.returncode == 0, "reference and actual output differ"


def test_all(act_dir="/tmp"):
    # run vectorized tests
    try:
        plot.use_vectorized_plot = True
        for name, str_expr in vectorized + both:
            one_test(name + "-vectorized", str_expr, act_dir)
    finally:
        plot.use_vectorized_plot = False

    # run classic tests
    for name, str_expr in classic + both:
        one_test(name, str_expr, act_dir)


if __name__ == "__main__":
    # reference files can be generated by pointing saved actual
    # output at reference dir instead of /tmp
    def make_ref_files():
        test_all(ref_dir())

    def run_tests():
        try:
            test_all()
        except AssertionError:
            print("FAIL")

    # make_ref_files()
    run_tests()
