# -*- coding: utf-8 -*-
"""
Symbols for some (but not all) Mathics3 primitive names

We put all of this in one place to make it easy to find most of them.

There are other Symbols, such as those for True and False that are
needed in the Symbol class. So those are defined there, not here.

Other modules may also define Symbols which are thought to be
lesser-used, or is will probably only be use in the module where it is
defined. Over time, as we find more uses of these, they are sometimes
moved here.

"""
from typing import Final

from mathics.core.symbols import Symbol, symbol_set

# Note that at the time this is evaluated Symbol("System`X")
# is the same as Symbol("X"), but it is better to make this
# explicit. A Pymathics module for example may decide to define
# its own Symbol X that also appears here after System`

# This list is sorted in alphabetic order.
SymbolAborted: Final[Symbol] = Symbol("System`$Aborted")
SymbolAbs: Final[Symbol] = Symbol("System`Abs")
SymbolAbsoluteThickness: Final[Symbol] = Symbol("System`AbsoluteThickness")
SymbolAbsoluteTime: Final[Symbol] = Symbol("AbsoluteTime")
SymbolAccuracy: Final[Symbol] = Symbol("System`Accuracy")
SymbolAlignmentPoint: Final[Symbol] = Symbol("System`AlignmentPoint")
SymbolAll: Final[Symbol] = Symbol("System`All")
SymbolAlternatives: Final[Symbol] = Symbol("System`Alternatives")
SymbolAnd: Final[Symbol] = Symbol("System`And")
SymbolAppend: Final[Symbol] = Symbol("System`Append")
SymbolAppendTo: Final[Symbol] = Symbol("System`AppendTo")
SymbolApply: Final[Symbol] = Symbol("System`Apply")
SymbolArcCos: Final[Symbol] = Symbol("System`ArcCos")
SymbolArcSin: Final[Symbol] = Symbol("System`ArcSin")
SymbolArcTan: Final[Symbol] = Symbol("System`ArcTan")
SymbolAspectRatio: Final[Symbol] = Symbol("System`AspectRatio")
SymbolAssociation: Final[Symbol] = Symbol("System`Association")
SymbolAssumptions: Final[Symbol] = Symbol("System`$Assumptions")
SymbolAttributes: Final[Symbol] = Symbol("System`Attributes")
SymbolAutomatic: Final[Symbol] = Symbol("System`Automatic")
SymbolAxes: Final[Symbol] = Symbol("System`Axes")
SymbolAxesEdge: Final[Symbol] = Symbol("System`AxesEdge")
SymbolAxesLabel: Final[Symbol] = Symbol("System`AxesLabel")
SymbolAxesOrigin: Final[Symbol] = Symbol("System`AxesOrigin")
SymbolAxesStyle: Final[Symbol] = Symbol("System`AxesStyle")
SymbolBackground: Final[Symbol] = Symbol("Sytem`Background")
SymbolBaseForm: Final[Symbol] = Symbol("System`BaseForm")
SymbolBaseStyle: Final[Symbol] = Symbol("System`BaseStyle")
SymbolBaselinePosition: Final[Symbol] = Symbol("System`BaselinePosition")
SymbolBlack: Final[Symbol] = Symbol("System`Black")
SymbolBlank: Final[Symbol] = Symbol("System`Blank")
SymbolBlankNullSequence: Final[Symbol] = Symbol("System`BlankNullSequence")
SymbolBlankSequence: Final[Symbol] = Symbol("System`BlankSequence")
SymbolBlend: Final[Symbol] = Symbol("System`Blend")
SymbolBooleans: Final[Symbol] = Symbol("System`Booleans")
SymbolBoxForms: Final[Symbol] = Symbol("System`$BoxForms")
SymbolBoxRatios: Final[Symbol] = Symbol("System`BoxRatios")
SymbolBoxStyle: Final[Symbol] = Symbol("System`BoxStyle")
SymbolBoxed: Final[Symbol] = Symbol("System`Boxed")
SymbolBreak: Final[Symbol] = Symbol("System`Break")
SymbolButtonBox: Final[Symbol] = Symbol("System`ButtonBox")
SymbolByteArray: Final[Symbol] = Symbol("System`ByteArray")
SymbolC: Final[Symbol] = Symbol("System`C")
SymbolCases: Final[Symbol] = Symbol("System`Cases")
SymbolCatalan: Final[Symbol] = Symbol("System`Catalan")
SymbolCeiling: Final[Symbol] = Symbol("System`Ceiling")
SymbolClearAttributes: Final[Symbol] = Symbol("System`ClearAttributes")
SymbolClipPlanes: Final[Symbol] = Symbol("System`ClipPlanes")
SymbolClipPlanesStyle: Final[Symbol] = Symbol("System`ClipPlanesStyle")
SymbolClusteringComponents: Final[Symbol] = Symbol("System`ClusteringComponents")
SymbolColorConvert: Final[Symbol] = Symbol("System`ColorConvert")
SymbolColorData: Final[Symbol] = Symbol("System`ColorData")
SymbolColorQuantize: Final[Symbol] = Symbol("System`ColorQuantize")
SymbolCompile: Final[Symbol] = Symbol("System`Compile")
SymbolCompiledFunction: Final[Symbol] = Symbol("System`CompiledFunction")
SymbolComplex: Final[Symbol] = Symbol("System`Complex")
SymbolComplexInfinity: Final[Symbol] = Symbol("System`ComplexInfinity")
SymbolComplexes: Final[Symbol] = Symbol("System`Complexes")
SymbolCondition: Final[Symbol] = Symbol("System`Condition")
SymbolConditionalExpression: Final[Symbol] = Symbol("System`ConditionalExpression")
SymbolConjugate: Final[Symbol] = Symbol("System`Conjugate")
SymbolContainsOnly: Final[Symbol] = Symbol("System`ContainsOnly")
SymbolContentSelectable: Final[Symbol] = Symbol("System`ContentSelectable")
SymbolContext: Final[Symbol] = Symbol("System`$Context")
SymbolContextPath: Final[Symbol] = Symbol("System`$ContextPath")
SymbolContinue: Final[Symbol] = Symbol("System`Continue")
SymbolControllerLinking: Final[Symbol] = Symbol("System`ControllerLinking")
SymbolControllerPath: Final[Symbol] = Symbol("System`ControllerPath")
SymbolCos: Final[Symbol] = Symbol("System`Cos")
SymbolCosh: Final[Symbol] = Symbol("System`Cosh")
SymbolCot: Final[Symbol] = Symbol("System`Cot")
SymbolCoth: Final[Symbol] = Symbol("System`Coth")
SymbolCovariance: Final[Symbol] = Symbol("System`Covariance")
SymbolCsc: Final[Symbol] = Symbol("System`Csc")
SymbolCsch: Final[Symbol] = Symbol("System`Csch")
SymbolD: Final[Symbol] = Symbol("System`D")
SymbolDefault: Final[Symbol] = Symbol("System`Default")
SymbolDefinition: Final[Symbol] = Symbol("System`Definition")
SymbolDeleteFile: Final[Symbol] = Symbol("System`DeleteFile")
SymbolDerivative: Final[Symbol] = Symbol("System`Derivative")
SymbolDigitCharacter: Final[Symbol] = Symbol("System`DigitCharacter")
SymbolDirectedInfinity: Final[Symbol] = Symbol("System`DirectedInfinity")
SymbolDirective: Final[Symbol] = Symbol("System`Directive")
SymbolDisk: Final[Symbol] = Symbol("System`Disk")
SymbolDiskBox: Final[Symbol] = Symbol("System`DiskBox")
SymbolDispatch: Final[Symbol] = Symbol("System`Dispatch")
SymbolDivide: Final[Symbol] = Symbol("System`Divide")
SymbolDot: Final[Symbol] = Symbol("System`Dot")
SymbolDownValues: Final[Symbol] = Symbol("System`DownValues")
SymbolDrop: Final[Symbol] = Symbol("System`Drop")
SymbolE: Final[Symbol] = Symbol("System`E")
SymbolEdgeForm: Final[Symbol] = Symbol("System`EdgeForm")
SymbolElement: Final[Symbol] = Symbol("System`Element")
SymbolEndOfFile: Final[Symbol] = Symbol("System`EndOfFile")
SymbolEndOfLine: Final[Symbol] = Symbol("System`EndOfLine")
SymbolEndOfString: Final[Symbol] = Symbol("System`EndOfString")
SymbolEpilog: Final[Symbol] = Symbol("System`Epilog")
SymbolEqual: Final[Symbol] = Symbol("System`Equal")
SymbolEquivalent: Final[Symbol] = Symbol("System`Equivalent")
SymbolEulerGamma: Final[Symbol] = Symbol("System`EulerGamma")
SymbolExactNumberQ: Final[Symbol] = Symbol("System`ExactNumberQ")
SymbolExp: Final[Symbol] = Symbol("System`Exp")
SymbolExpandAll: Final[Symbol] = Symbol("System`ExpandAll")
SymbolExport: Final[Symbol] = Symbol("System`Export")
SymbolExportString: Final[Symbol] = Symbol("System`ExportString")
SymbolExpression: Final[Symbol] = Symbol("System`Expression")
SymbolFaceForm: Final[Symbol] = Symbol("System`FaceForm")
SymbolFaceGrids: Final[Symbol] = Symbol("System`FaceGrids")
SymbolFaceGridsStyle: Final[Symbol] = Symbol("System`FaceGridsStyle")
SymbolFactorial: Final[Symbol] = Symbol("System`Factorial")
SymbolFailed: Final[Symbol] = Symbol("System`$Failed")
SymbolFileExtension: Final[Symbol] = Symbol("System`FileExtension")
SymbolFileFormat: Final[Symbol] = Symbol("System`FileFormat")
SymbolFindClusters: Final[Symbol] = Symbol("System`FindClusters")
SymbolFindFile: Final[Symbol] = Symbol("System`FindFile")
SymbolFirst: Final[Symbol] = Symbol("System`First")
SymbolFloor: Final[Symbol] = Symbol("System`Floor")
SymbolFormBox: Final[Symbol] = Symbol("System`FormBox")
SymbolFormat: Final[Symbol] = Symbol("System`Format")
SymbolFormatType: Final[Symbol] = Symbol("System`FormatType")
SymbolFractionBox: Final[Symbol] = Symbol("System`FractionBox")
SymbolFrameLabel: Final[Symbol] = Symbol("System`FrameLabel")
SymbolFull: Final[Symbol] = Symbol("System`Full")
SymbolFullForm: Final[Symbol] = Symbol("System`FullForm")
SymbolFunction: Final[Symbol] = Symbol("System`Function")
SymbolGamma: Final[Symbol] = Symbol("System`Gamma")
SymbolGet: Final[Symbol] = Symbol("System`Get")
SymbolGlaisher: Final[Symbol] = Symbol("System`Glaisher")
SymbolGoldenRatio: Final[Symbol] = Symbol("System`GoldenRatio")
SymbolGraphics: Final[Symbol] = Symbol("System`Graphics")
SymbolGraphics3D: Final[Symbol] = Symbol("System`Graphics3D")
SymbolGraphics3DBox: Final[Symbol] = Symbol("System`Graphics3DBox")
SymbolGraphicsBox: Final[Symbol] = Symbol("System`GraphicsBox")
SymbolGraphicsComplex: Final[Symbol] = Symbol("System`GraphicsComplex")
SymbolGraphicsComplexBox: Final[Symbol] = Symbol("System`GraphicsComplexBox")
SymbolGreater: Final[Symbol] = Symbol("System`Greater")
SymbolGreaterEqual: Final[Symbol] = Symbol("System`GreaterEqual")
SymbolGrid: Final[Symbol] = Symbol("System`Grid")
SymbolGridBox: Final[Symbol] = Symbol("System`GridBox")
SymbolHexadecimalCharacter: Final[Symbol] = Symbol("System`HexadecimalCharacter")
SymbolHold: Final[Symbol] = Symbol("System`Hold")
SymbolHoldExpression: Final[Symbol] = Symbol("System`HoldExpression")
SymbolHoldForm: Final[Symbol] = Symbol("System`HoldForm")
SymbolHoldPattern: Final[Symbol] = Symbol("System`HoldPattern")
SymbolHue: Final[Symbol] = Symbol("System`Hue")
SymbolI: Final[Symbol] = Symbol("System`I")
SymbolIdentity: Final[Symbol] = Symbol("System`Identity")
SymbolIf: Final[Symbol] = Symbol("System`If")
SymbolIm: Final[Symbol] = Symbol("System`Im")
SymbolImage: Final[Symbol] = Symbol("System`Image")
SymbolImageMargins: Final[Symbol] = Symbol("System`ImageMargins")
SymbolImagePadding: Final[Symbol] = Symbol("System`ImagePadding")
SymbolImageSize: Final[Symbol] = Symbol("System`ImageSize")
SymbolImplies: Final[Symbol] = Symbol("System`Implies")
SymbolIn: Final[Symbol] = Symbol("System`In")
SymbolIndeterminate: Final[Symbol] = Symbol("System`Indeterminate")
SymbolInequality: Final[Symbol] = Symbol("System`Inequality")
SymbolInfinity: Final[Symbol] = Symbol("System`Infinity")
SymbolInfix: Final[Symbol] = Symbol("System`Infix")
SymbolInformationData: Final[Symbol] = Symbol("System`InformationData")
SymbolInformationDataGrid: Final[Symbol] = Symbol("System`InformationDataGrid")
SymbolInner: Final[Symbol] = Symbol("System`Inner")
SymbolInputForm: Final[Symbol] = Symbol("System`InputForm")
SymbolInputStream: Final[Symbol] = Symbol("System`InputStream")
SymbolInset: Final[Symbol] = Symbol("System`Inset")
SymbolInsetBox: Final[Symbol] = Symbol("System`InsetBox")
SymbolInteger: Final[Symbol] = Symbol("System`Integer")
SymbolIntegers: Final[Symbol] = Symbol("System`Integers")
SymbolIntegrate: Final[Symbol] = Symbol("System`Integrate")
SymbolInterpretationBox: Final[Symbol] = Symbol("System`InterpretationBox")
SymbolKey: Final[Symbol] = Symbol("System`Key")
SymbolKeyAbsent: Final[Symbol] = Symbol("System`KeyAbsent")
SymbolKhinchin: Final[Symbol] = Symbol("System`Khinchin")
SymbolLabelStyle: Final[Symbol] = Symbol("System`LabelStyle")
SymbolLast: Final[Symbol] = Symbol("System`Last")
SymbolLeft: Final[Symbol] = Symbol("System`Left")
SymbolLength: Final[Symbol] = Symbol("System`Length")
SymbolLess: Final[Symbol] = Symbol("System`Less")
SymbolLessEqual: Final[Symbol] = Symbol("System`LessEqual")
SymbolLetterCharacter: Final[Symbol] = Symbol("System`LetterCharacter")
SymbolLighting: Final[Symbol] = Symbol("System`Lighting")
SymbolLine: Final[Symbol] = Symbol("System`Line")
SymbolLine3DBox: Final[Symbol] = Symbol("System`Line3DBox")
SymbolLineBox: Final[Symbol] = Symbol("System`LineBox")
SymbolList: Final[Symbol] = Symbol("System`List")
SymbolLog: Final[Symbol] = Symbol("System`Log")
SymbolLog10: Final[Symbol] = Symbol("System`Log10")
SymbolLogPlot: Final[Symbol] = Symbol("System`LogPlot")
SymbolMachinePrecision: Final[Symbol] = Symbol("System`MachinePrecision")
SymbolMakeBoxes: Final[Symbol] = Symbol("System`MakeBoxes")
SymbolManipulate: Final[Symbol] = Symbol("System`Manipulate")
SymbolManipulateBox: Final[Symbol] = Symbol("System`ManipulateBox")
SymbolMap: Final[Symbol] = Symbol("System`Map")
SymbolMapAt: Final[Symbol] = Symbol("System`MapAt")
SymbolMapThread: Final[Symbol] = Symbol("System`MapThread")
SymbolMatchQ: Final[Symbol] = Symbol("System`MatchQ")
SymbolMathMLForm: Final[Symbol] = Symbol("System`MathMLForm")
SymbolMatrixPower: Final[Symbol] = Symbol("System`MatrixPower")
SymbolMatrixQ: Final[Symbol] = Symbol("System`MatrixQ")
SymbolMax: Final[Symbol] = Symbol("System`Max")
SymbolMaxExtraPrecision: Final[Symbol] = Symbol("System`$MaxExtraPrecision")
SymbolMaxPrecision: Final[Symbol] = Symbol("System`$MaxPrecision")
SymbolMean: Final[Symbol] = Symbol("System`Mean")
SymbolMedian: Final[Symbol] = Symbol("System`Median")
SymbolMemberQ: Final[Symbol] = Symbol("System`MemberQ")
SymbolMessageName: Final[Symbol] = Symbol("System`MessageName")
SymbolMessages: Final[Symbol] = Symbol("System`Messages")
SymbolMethod: Final[Symbol] = Symbol("System`Method")
SymbolMinus: Final[Symbol] = Symbol("System`Minus")
SymbolMissing: Final[Symbol] = Symbol("System`Missing")
SymbolN: Final[Symbol] = Symbol("System`N")
SymbolNIntegrate: Final[Symbol] = Symbol("System`NIntegrate")
SymbolNValues: Final[Symbol] = Symbol("System`NValues")
SymbolNand: Final[Symbol] = Symbol("System`Nand")
SymbolNeeds: Final[Symbol] = Symbol("System`Needs")
SymbolNor: Final[Symbol] = Symbol("System`Nor")
SymbolNonAssociative: Final[Symbol] = Symbol("System`NonAssociative")
SymbolNone: Final[Symbol] = Symbol("System`None")
SymbolNorm: Final[Symbol] = Symbol("System`Norm")
SymbolNormal: Final[Symbol] = Symbol("System`Normal")
SymbolNot: Final[Symbol] = Symbol("System`Not")
SymbolNothing: Final[Symbol] = Symbol("System`Nothing")
SymbolNumberForm: Final[Symbol] = Symbol("System`NumberForm")
SymbolNumberQ: Final[Symbol] = Symbol("System`NumberQ")
SymbolNumberString: Final[Symbol] = Symbol("System`NumberString")
SymbolNumericQ: Final[Symbol] = Symbol("System`NumericQ")
SymbolO: Final[Symbol] = Symbol("System`O")
SymbolOffset: Final[Symbol] = Symbol("System`Offset")
SymbolOpacity: Final[Symbol] = Symbol("System`Opacity")
SymbolOpenWrite: Final[Symbol] = Symbol("System`OpenWrite")
SymbolOperate: Final[Symbol] = Symbol("System`Operate")
SymbolOptionValue: Final[Symbol] = Symbol("System`OptionValue")
SymbolOptional: Final[Symbol] = Symbol("System`Optional")
SymbolOptions: Final[Symbol] = Symbol("System`Options")
SymbolOptionsPattern: Final[Symbol] = Symbol("System`OptionsPattern")
SymbolOr: Final[Symbol] = Symbol("System`Or")
SymbolOut: Final[Symbol] = Symbol("System`Out")
SymbolOuter: Final[Symbol] = Symbol("System`Outer")
SymbolOutputForm: Final[Symbol] = Symbol("System`OutputForm")
SymbolOutputStream: Final[Symbol] = Symbol("System`OutputStream")
SymbolOverflow: Final[Symbol] = Symbol("System`Overflow")
SymbolOwnValues: Final[Symbol] = Symbol("System`OwnValues")
SymbolPackages: Final[Symbol] = Symbol("System`$Packages")
SymbolPaneBox: Final[Symbol] = Symbol("System`PaneBox")
SymbolParentForm: Final[Symbol] = Symbol("System`ParentForm")
SymbolPart: Final[Symbol] = Symbol("System`Part")
SymbolPath: Final[Symbol] = Symbol("System`$Path")
SymbolPattern: Final[Symbol] = Symbol("System`Pattern")
SymbolPatternTest: Final[Symbol] = Symbol("System`PatternTest")
SymbolPause: Final[Symbol] = Symbol("System`Pause")
SymbolPi: Final[Symbol] = Symbol("System`Pi")
SymbolPiecewise: Final[Symbol] = Symbol("System`Piecewise")
SymbolPlot: Final[Symbol] = Symbol("System`Plot")
SymbolPlotLabel: Final[Symbol] = Symbol("System`PlotLabel")
SymbolPlotRange: Final[Symbol] = Symbol("System`PlotRange")
SymbolPlotRangeClipping: Final[Symbol] = Symbol("System`PlotRangeClipping")
SymbolPlotRangePadding: Final[Symbol] = Symbol("System`PlotRangePadding")
SymbolPlotRegion: Final[Symbol] = Symbol("System`PlotRegion")
SymbolPlus: Final[Symbol] = Symbol("System`Plus")
SymbolPoint: Final[Symbol] = Symbol("System`Point")
SymbolPointBox: Final[Symbol] = Symbol("System`PointBox")
SymbolPolygon: Final[Symbol] = Symbol("System`Polygon")
SymbolPolygon3DBox: Final[Symbol] = Symbol("Symbol`Polygon3DBox")
SymbolPolygonBox: Final[Symbol] = Symbol("Symbol`PolygonBox")
SymbolPossibleZeroQ: Final[Symbol] = Symbol("System`PossibleZeroQ")
SymbolPostfix: Final[Symbol] = Symbol("System`Postfix")
SymbolPower: Final[Symbol] = Symbol("System`Power")
SymbolPrecision: Final[Symbol] = Symbol("System`Precision")
SymbolPrecedenceForm: Final[Symbol] = Symbol("System`PrecedenceForm")
SymbolPrefix: Final[Symbol] = Symbol("System`Prefix")
SymbolPrime: Final[Symbol] = Symbol("System`Prime")
SymbolPreserveImageOptions: Final[Symbol] = Symbol("System`PreserveImageOptions")
SymbolProduct: Final[Symbol] = Symbol("System`Product")
SymbolProlog: Final[Symbol] = Symbol("System`Prolog")
SymbolProtected: Final[Symbol] = Symbol("System`Protected")
SymbolQuantity: Final[Symbol] = Symbol("System`Quantity")
SymbolQuiet: Final[Symbol] = Symbol("System`Quiet")
SymbolQuotient: Final[Symbol] = Symbol("System`Quotient")
SymbolQuotientRemainder: Final[Symbol] = Symbol("System`QuotientRemainder")
SymbolRGBColor: Final[Symbol] = Symbol("System`RGBColor")
SymbolRandomComplex: Final[Symbol] = Symbol("System`RandomComplex")
SymbolRandomReal: Final[Symbol] = Symbol("System`RandomReal")
SymbolRange: Final[Symbol] = Symbol("Range")
SymbolRankedMax: Final[Symbol] = Symbol("RankedMax")
SymbolRankedMin: Final[Symbol] = Symbol("RankedMin")
SymbolRational: Final[Symbol] = Symbol("System`Rational")
SymbolRationals: Final[Symbol] = Symbol("System`Rationals")
SymbolRe: Final[Symbol] = Symbol("System`Re")
SymbolReal: Final[Symbol] = Symbol("System`Real")
SymbolReals: Final[Symbol] = Symbol("System`Reals")
SymbolRealAbs: Final[Symbol] = Symbol("System`RealAbs")
SymbolRealDigits: Final[Symbol] = Symbol("System`RealDigits")
SymbolRealSign: Final[Symbol] = Symbol("System`RealSign")
SymbolRectangle: Final[Symbol] = Symbol("System`Rectangle")
SymbolRectangleBox: Final[Symbol] = Symbol("System`RectangleBox")
SymbolRepeated: Final[Symbol] = Symbol("System`Repeated")
SymbolRepeatedNull: Final[Symbol] = Symbol("System`RepeatedNull")
SymbolReplaceList: Final[Symbol] = Symbol("System`ReplaceList")
SymbolReturn: Final[Symbol] = Symbol("System`Return")
SymbolReverse: Final[Symbol] = Symbol("System`Reverse")
SymbolRight: Final[Symbol] = Symbol("System`Right")
SymbolRoot: Final[Symbol] = Symbol("System`Root")
SymbolRootSum: Final[Symbol] = Symbol("System`RootSum")
SymbolRotationAction: Final[Symbol] = Symbol("System`RotationAction")
SymbolRound: Final[Symbol] = Symbol("System`Round")
SymbolRow: Final[Symbol] = Symbol("System`Row")
SymbolRowBox: Final[Symbol] = Symbol("System`RowBox")
SymbolRule: Final[Symbol] = Symbol("System`Rule")
SymbolRuleDelayed: Final[Symbol] = Symbol("System`RuleDelayed")
SymbolSameQ: Final[Symbol] = Symbol("System`SameQ")
SymbolSelect: Final[Symbol] = Symbol("System`Select")
SymbolSequence: Final[Symbol] = Symbol("System`Sequence")
SymbolSeries: Final[Symbol] = Symbol("System`Series")
SymbolSeriesData: Final[Symbol] = Symbol("System`SeriesData")
SymbolSet: Final[Symbol] = Symbol("System`Set")
SymbolSetAttributes: Final[Symbol] = Symbol("System`SetAttributes")
SymbolSign: Final[Symbol] = Symbol("System`Sign")
SymbolSimplify: Final[Symbol] = Symbol("System`Simplify")
SymbolSin: Final[Symbol] = Symbol("System`Sin")
SymbolSinh: Final[Symbol] = Symbol("System`Sinh")
SymbolSlot: Final[Symbol] = Symbol("System`Slot")
SymbolSort: Final[Symbol] = Symbol("System`Sort")
SymbolSortBy: Final[Symbol] = Symbol("System`SortBy")
SymbolSpan: Final[Symbol] = Symbol("System`Span")
SymbolSparseArray: Final[Symbol] = Symbol("System`SparseArray")
SymbolSphere: Final[Symbol] = Symbol("System`Sphere")
SymbolSphereBox: Final[Symbol] = Symbol("System`SphereBox")
SymbolSphericalRegion: Final[Symbol] = Symbol("System`SphericalRegion")
SymbolSplit: Final[Symbol] = Symbol("System`Split")
SymbolSqrt: Final[Symbol] = Symbol("System`Sqrt")
SymbolSqrtBox: Final[Symbol] = Symbol("System`SqrtBox")
SymbolStandardDeviation: Final[Symbol] = Symbol("System`StandardDeviation")
SymbolStandardForm: Final[Symbol] = Symbol("System`StandardForm")
SymbolStartOfLine: Final[Symbol] = Symbol("System`StartOfLine")
SymbolStartOfString: Final[Symbol] = Symbol("System`StartOfString")
SymbolString: Final[Symbol] = Symbol("System`String")
SymbolStringExpression: Final[Symbol] = Symbol("System`StringExpression")
SymbolStringForm: Final[Symbol] = Symbol("System`StringForm")
SymbolStringInsert: Final[Symbol] = Symbol("System`StringInsert")
SymbolStringJoin: Final[Symbol] = Symbol("System`StringJoin")
SymbolStringMatchQ: Final[Symbol] = Symbol("System`StringMatchQ")
SymbolStringPosition: Final[Symbol] = Symbol("System`StringPosition")
SymbolStringQ: Final[Symbol] = Symbol("System`StringQ")
SymbolStringRiffle: Final[Symbol] = Symbol("System`StringRiffle")
SymbolStringSplit: Final[Symbol] = Symbol("System`StringSplit")
SymbolStringToStream: Final[Symbol] = Symbol("System`StringToStream")
SymbolStyle: Final[Symbol] = Symbol("System`Style")
SymbolStyleBox: Final[Symbol] = Symbol("System`StyleBox")
SymbolSubValues: Final[Symbol] = Symbol("System`SubValues")
SymbolSubscriptBox: Final[Symbol] = Symbol("System`SubscriptBox")
SymbolSubsetQ: Final[Symbol] = Symbol("System`SubsetQ")
SymbolSubsuperscriptBox: Final[Symbol] = Symbol("System`SubsuperscriptBox")
SymbolSubtract: Final[Symbol] = Symbol("System`Subtract")
SymbolSum: Final[Symbol] = Symbol("System`Sum")
SymbolSuperscriptBox: Final[Symbol] = Symbol("System`SuperscriptBox")
SymbolTable: Final[Symbol] = Symbol("System`Table")
SymbolTableForm: Final[Symbol] = Symbol("System`TableForm")
SymbolTagBox: Final[Symbol] = Symbol("System`TagBox")
SymbolTake: Final[Symbol] = Symbol("System`Take")
SymbolTan: Final[Symbol] = Symbol("System`Tan")
SymbolTanh: Final[Symbol] = Symbol("System`Tanh")
SymbolTeXForm: Final[Symbol] = Symbol("System`TeXForm")
SymbolText: Final[Symbol] = Symbol("System`Text")
SymbolThreshold: Final[Symbol] = Symbol("System`Threshold")
SymbolThrow: Final[Symbol] = Symbol("System`Throw")
SymbolTicks: Final[Symbol] = Symbol("System`Ticks")
SymbolTicksStyle: Final[Symbol] = Symbol("System`TicksStyle")
SymbolTimes: Final[Symbol] = Symbol("System`Times")
SymbolToBoxes: Final[Symbol] = Symbol("System`ToBoxes")
SymbolToExpression: Final[Symbol] = Symbol("System`ToExpression")
SymbolToString: Final[Symbol] = Symbol("System`ToString")
SymbolTotal: Final[Symbol] = Symbol("System`Total")
SymbolTooltipBox: Final[Symbol] = Symbol("System`TooltipBox")
SymbolTouchscreenAutoZoom: Final[Symbol] = Symbol("System`TouchscreenAutoZoom")
SymbolTraditionalForm: Final[Symbol] = Symbol("System`TraditionalForm")
SymbolTuples: Final[Symbol] = Symbol("System`Tuples")
SymbolUndefined: Final[Symbol] = Symbol("System`Undefined")
SymbolUnequal: Final[Symbol] = Symbol("System`Unequal")
SymbolUnevaluated: Final[Symbol] = Symbol("System`Unevaluated")
SymbolUnknownProperty: Final[Symbol] = Symbol("System`UnknownProperty")
SymbolUnknownSymbol: Final[Symbol] = Symbol("System`UnknownSymbol")
SymbolUpValues: Final[Symbol] = Symbol("System`UpValues")
SymbolVariance: Final[Symbol] = Symbol("System`Variance")
SymbolVerbatim: Final[Symbol] = Symbol("Verbatim")
SymbolVertexColors: Final[Symbol] = Symbol("VertexColors")
SymbolViewAngle: Final[Symbol] = Symbol("System`ViewAngle")
SymbolViewCenter: Final[Symbol] = Symbol("System`ViewCenter")
SymbolViewMatrix: Final[Symbol] = Symbol("System`ViewMatrix")
SymbolViewPoint: Final[Symbol] = Symbol("System`ViewPoint")
SymbolViewProjection: Final[Symbol] = Symbol("System`ViewProjection")
SymbolViewRange: Final[Symbol] = Symbol("System`ViewRange")
SymbolViewVector: Final[Symbol] = Symbol("System`ViewVector")
SymbolViewVertical: Final[Symbol] = Symbol("System`ViewVertical")
SymbolWhitespace: Final[Symbol] = Symbol("System`Whitespace")
SymbolWhitespaceCharacter: Final[Symbol] = Symbol("System`WhitespaceCharacter")
SymbolWord: Final[Symbol] = Symbol("System`Word")
SymbolWordBoundary: Final[Symbol] = Symbol("System`WordBoundary")
SymbolWordCharacter: Final[Symbol] = Symbol("System`WordCharacter")
SymbolWriteString: Final[Symbol] = Symbol("System`WriteString")
SymbolXor: Final[Symbol] = Symbol("System`Xor")


##### Special symbol sets


BLANK_PATTERN_HEADS = symbol_set(
    SymbolBlank,
    SymbolBlankNullSequence,
    SymbolBlankSequence,
)

RULE_SYMBOL_HEADS = symbol_set(SymbolRule, SymbolRuleDelayed)

SYSTEM_SYMBOLS_PATTERNS = symbol_set(
    SymbolAlternatives,
    SymbolBlank,
    SymbolBlankNullSequence,
    SymbolBlankSequence,
    SymbolCondition,
    SymbolOptional,
    SymbolOptionsPattern,
    SymbolPattern,
    SymbolPatternTest,
    SymbolRepeated,
    SymbolRepeatedNull,
)

SYSTEM_SYMBOL_VALUES = symbol_set(
    SymbolDownValues,
    SymbolMessages,
    SymbolNValues,
    SymbolOptions,
    SymbolOwnValues,
    SymbolSubValues,
    SymbolUpValues,
)
